[package]
name = "adder"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which adds to a number as its state transition"

[dependencies]
polkadot-parachain = { path = "../../parachain/", default-features = false }
parity-codec = { version = "3.5.1", default-features = false }
parity-codec-derive = { version = "3.3.0", default-features = false }
tiny-keccak = "1.4.2"
