[package]
name = "polkadot-cli"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Polkadot node implementation in Rust."

[dependencies]
log = "0.4.6"
tokio = "0.1.19"
futures = "0.1.26"
exit-future = "0.1.4"
substrate-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
polkadot-service = { path = "../service" }
