[package]
name = "adder-collator"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
adder = { path = ".." }
polkadot-parachain = { path = "../../../parachain" }
polkadot-collator = { path = "../../../collator" }
polkadot-primitives = { path = "../../../primitives" }
substrate-primitives = { git = "https://github.com/paritytech/substrate", branch = "polkadot-master" }
parking_lot = "0.8.0"
ctrlc = { version = "3.1.2", features = ["termination"] }
futures = "0.1.26"
exit-future = "0.1.4"
