[package]
name = "polkadot-parachain"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Types and utilities for creating and working with parachains"

[dependencies]
parity-codec = { version = "3.5.1", default-features = false }
parity-codec-derive = { version = "3.3.0", default-features = false }
wasmi = { version = "0.4.5", optional = true }
error-chain = { version = "0.12.0", optional = true }
serde = { version = "1.0.91", default-features = false }
serde_derive = { version = "1.0.91", optional = true }

[dev-dependencies]
tiny-keccak = "1.4.2"

[features]
default = ["std"]
wasm-api = []
std = ["parity-codec/std", "wasmi", "error-chain", "serde_derive", "serde/std"]
